# Moon
- platform: moon

# Systemmonitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
#    - type: swap_use_percent
#    - type: network_in
#      arg: eht0
#    - type: network_out
#      arg: eth0
#    - type: packets_in
#      arg: eth0
#    - type: packets_out
#      arg: eth0
#    - type: last_boot
#    - type: since_last_boot

# Yr Weather
- platform: yr
  name: !secret yr_location
  forecast: 24
  monitored_conditions:
    - temperature
    - precipitation
    - windSpeed
    - windDirection
    - humidity
    - pressure
    - fog
    - cloudiness
    - dewpointTemperature
    - lowClouds
    - mediumClouds
    - highClouds

# LastFM
#- platform: lastfm
#  api_key: !secret lastfm_api_key
#  users:
#    - !secret lastfm_users


- platform: statistics
  name: yttertemperatur
  entity_id: sensor.yr_temperature
- platform: api_streams

- platform: template
  sensors: 
    hue_kitchen_temp:
      friendly_name: "Hue Kitchen Temp"
      value_template: '{{ states.sensor.kitchen_motion_sensor.attributes.temperature | round(1) }}'
      unit_of_measurement: '°C'
    hue_kitchen_battery:
      friendly_name: "Hue Kitchen Battery"
      value_template: '{{ states.sensor.kitchen_motion_sensor.attributes.battery }}'
      unit_of_measurement: '%'
    hue_kitchen_light:
      friendly_name: "Hue Kitchen Light"
      value_template: '{{ states.sensor.kitchen_motion_sensor.attributes.lux| round(0) }}'
      unit_of_measurement: 'Lux'
    hue_entre_temp:
      friendly_name: "Hue Entré Temp"
      value_template: '{{ states.sensor.entre_motion_sensor.attributes.temperature | round(1) }}'
      unit_of_measurement: '°C'
    hue_entre_battery:
      friendly_name: "Hue Entré Battery"
      value_template: '{{ states.sensor.entre_motion_sensor.attributes.battery }}'
      unit_of_measurement: '%'
    hue_entre_light:
      friendly_name: "Hue Entré Light"
      value_template: '{{ states.sensor.entre_motion_sensor.attributes.lux| round(0) }}'
      unit_of_measurement: 'Lux'
    fibaro_eye_battery:
      friendly_name: "Fibaro Eye Battery"
      value_template: '{{ states.zwave.fibaro_eye.attributes.battery_level }}'
      unit_of_measurement: '%'
    fibaro_door_sensor_battery:
      friendly_name: "Fibaro Door Sensor Battery"
      value_template: '{{ states.zwave.fibaro_door_sensor.attributes.battery_level }}'
      unit_of_measurement: '%'
    indoor_min_temp:
      friendly_name: "Indoor Min Temp"
      value_template: '{{ states.sensor.max_sensor.attributes.min_value }}'
      unit_of_measurement: '°C'
    indoor_average_temp:
      friendly_name: "Indoor Average Temp"
      value_template: '{{ states.sensor.max_sensor.attributes.mean }}'
      unit_of_measurement: '°C'


- platform: season
  type: astronomical
- platform: airvisual
  api_key: !secret airvisual_api_key
  monitored_conditions: us
  city: !secret airvisual_city
  state: !secret airvisual_state
  country: !secret airvisual_country
  radius: 30000

- platform: hue

- platform: min_max
  entity_ids:
    - sensor.hue_kitchen_temp
    - sensor.hue_entre_temp
    - sensor.multisensor_6_temperature
    - sensor.fibaro_eye_temperature